name: build
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@78bd24e01a1a907f7ea3e614b4d7c15e563585a8
      with:
        go-version: 1.14
      id: go
    - name: Checkout
      uses: actions/checkout@94c2de77cccf605d74201a8aec6dd8fc0717ad66
    - name: vet
      run: go vet
    - name: test
      run: go test
    - name: build
      run: env GOOS=linux GOARCH=amd64 go build



